spring.application.name=IMS
spring.datasource.url=jdbc:mysql://localhost:3306/ims_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cacelasync@gmail.com
spring.mail.password=lzel lccq ueoe bouc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
twilio.account_sid=AC1855048da3d074129ca643fe3c9fedd0
twilio.auth_token=e2e6d025ddf4b148f1fa7a28acd33776
twilio.trial_number=+17077026612